"""Initial migration

Revision ID: 128c7330b8df
Revises: 
Create Date: 2025-03-23 00:47:43.385428
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '128c7330b8df'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('purchase_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('purchase_count')
        batch_op.drop_column('video_url')
    # ### end Alembic commands ###
